ALTER TABLE CIR_PRESTAMOS DROP COLUMN BIB_X_BIBLIOTECA_EJE;
ALTER TABLE CIR_PRESTAMOS DROP COLUMN BIB_X_BIBLIOTECA_LEC;
ALTER TABLE CIR_PRESTAMOS DROP COLUMN EJE_ESTA_X_EJEMPLAR_ESTADO;
ALTER TABLE CIR_PRESTAMOS DROP COLUMN EJE_LOCA_X_EJEMPLAR_LOCALIZ;
ALTER TABLE CIR_PRESTAMOS DROP COLUMN EJE_SOP_X_EJEMPLAR_SOPORTE;
ALTER TABLE CIR_PRESTAMOS DROP COLUMN EJE_TIPO_X_EJEMPLAR_TIPO;

ALTER TABLE CIR_PRESTAMOS_HIST DROP COLUMN BIB_X_BIBLIOTECA_EJE;
ALTER TABLE CIR_PRESTAMOS_HIST DROP COLUMN BIB_X_BIBLIOTECA_LEC;
ALTER TABLE CIR_PRESTAMOS_HIST DROP COLUMN EJE_ESTA_X_EJEMPLAR_ESTADO;
ALTER TABLE CIR_PRESTAMOS_HIST DROP COLUMN EJE_LOCA_X_EJEMPLAR_LOCALIZ;
ALTER TABLE CIR_PRESTAMOS_HIST DROP COLUMN EJE_SOP_X_EJEMPLAR_SOPORTE;
ALTER TABLE CIR_PRESTAMOS_HIST DROP COLUMN EJE_TIPO_X_EJEMPLAR_TIPO;