//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-520
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2009.12.01 at 12:50:36 PM CET
//

package org.librae.adminconfig.webapp.ws.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ConsultaType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;ConsultaType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;codBiblioteca&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsultaType", propOrder = { "codBiblioteca" })
@XmlRootElement
public class ConsultaType {

    @XmlElement(required = true)
    protected String codBiblioteca;

    /**
     * Gets the value of the codBiblioteca property.
     * 
     * @return possible object is {@link String }
     */
    public String getCodBiblioteca() {
        return codBiblioteca;
    }

    /**
     * Sets the value of the codBiblioteca property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setCodBiblioteca(String value) {
        codBiblioteca = value;
    }

}
