//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-520
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2009.12.01 at 12:50:36 PM CET
//

package org.librae.adminconfig.webapp.ws.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for RespuestaType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;RespuestaType&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;Horario&quot; type=&quot;{http://horario.ws.librae.org/}Horario&quot;/&gt;
 *         &lt;element name=&quot;Error&quot; type=&quot;{http://horario.ws.librae.org/}Error&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RespuestaType", propOrder = { "horario", "error" })
@XmlRootElement
public class Respuesta {

    @XmlElement(name = "Horario", required = true)
    protected Horario horario;
    @XmlElement(name = "Error", required = true)
    protected Error   error;

    /**
     * Gets the value of the horario property.
     * 
     * @return possible object is {@link Horario }
     */
    public Horario getHorario() {
        return horario;
    }

    /**
     * Sets the value of the horario property.
     * 
     * @param value
     *            allowed object is {@link Horario }
     */
    public void setHorario(Horario value) {
        horario = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return possible object is {@link Error }
     */
    public Error getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *            allowed object is {@link Error }
     */
    public void setError(Error value) {
        error = value;
    }

}
