DROP TABLE ADM_VIEW_BIBLIOTECA; 
 
CREATE OR REPLACE VIEW ADM_VIEW_BIBLIOTECA AS
  SELECT b.X_BIBLIOTECA AS X_VIEW_BIBLIOTECA,
    b.BIB_X_BIBLIOTECA  AS BIBLIOTECA_X_PADRE,
    b.T_BIBLIOTECA      AS T_DESCRIPCION,
	b.C_BIBLIOTECA		AS T_CODIGO,
    t.C_TIPO_BIBLIOTECA AS TIPO_BIBLIOTECA
 FROM ADM_BIBLIOTECAS b,ADM_TIPOS_BIBLIOTECA t
 WHERE b.TIP_X_TIPO_BIBLIOTECA=t.X_TIPO_BIBLIOTECA;
