insert into CIR_PIB_TIPOS_PETICIONES values (-1,'Materiales no retornables','#tipoPeticion.pib.materialesNoRetornables',null);
insert into CIR_PIB_TIPOS_PETICIONES values (-2,'Estimación de coste','#tipoPeticion.pib.estimacionCoste',null);
insert into CIR_PIB_TIPOS_PETICIONES values (-3,'Reserva','#tipoPeticion.pib.reserva',null);
insert into CIR_PIB_TIPOS_PETICIONES values (-4,'Préstamo','#tipoPeticion.pib.prestamo',null);
insert into CIR_PIB_TIPOS_PETICIONES values (-5,'Petición a Depósito','#tipoPeticion.pib.peticionDeposito',null);

insert into CIR_PIB_ESTADOS_PETICIONES values (-1,'Evaluación','#estadoPeticionPIB.evaluacion',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-2,'Petición generada','#estadoPeticionPIB.peticionGenerada',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-3,'Préstamo pedido','#estadoPeticionPIB.prestamoPedido',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-4,'Préstamo registrado','#estadoPeticionPIB.prestamoRegistrado',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-5,'Envío registrado','#estadoPeticionPIB.envioRegistrado',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-6,'Material recibido de la bib. prestamista','#estadoPeticionPIB.materialRecibidoPrestamista',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-7,'Material recibido','#estadoPeticionPIB.materialRecibido',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-8,'Préstamo en curso','#estadoPeticionPIB.gestionPrestamo',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-9,'Préstamo renovado','#estadoPeticionPIB.prestamoRenovado',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-10,'Préstamo devuelto','#estadoPeticionPIB.prestamoDevuelto',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-11,'Material enviado a la bib. prestamista','#estadoPeticionPIB.materialEnviadoPrestamista',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-12,'Entrega realizada en la bib. prestamista','#estadoPeticionPIB.entregaRealizadaPrestamista',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-13,'Préstamo devuelto en la bib. prestataria','#estadoPeticionPIB.prestamoDevueltoPrestataria',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-14,'Petición de préstamo recibida','#estadoPeticionPIB.peticionPrestamoRecibida',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-15,'Préstamo realizado en la bib. prestamista','#estadoPeticionPIB.enviarMaterialPrestamista',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-16,'Material enviado a la bib. prestataria','#estadoPeticionPIB.materialEnviadoPrestataria',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-17,'Entrega realizada en la bib. prestataria','#estadoPeticionPIB.entregaRealizadaPrestataria',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-18,'Entrega realizada en la bib. prestataria','#estadoPeticionPIB.entregaRealizadaPrestataria',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-19,'Registrado envío de devolución','#estadoPeticionPIB.registradoEnvioDevolucion',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-20,'Material devuelto recepcionado','#estadoPeticionPIB.materialDevueltoRecepcionado',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-21,'Material restituido','#estadoPeticionPIB.materialRestituido',null);
insert into CIR_PIB_ESTADOS_PETICIONES values (-22,'Cerrada','#estadoPeticionPIB.cerrada',null);

INSERT INTO CIR_PARAMETROS ( X_PARAMETRO, D_PRIOR_ENTRE_TIPOS_RESER, D_TIPO_LECTOR_SI_VARIOS,POL_DEF_X_DOM_POL_PREST_DEFECT, POL_DEF_X_RES_POLIT_PREST_DEF ) VALUES ( 1, NULL, NULL, 2, 2);
commit;
