insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (208, 0, '740', 'Surinam');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (209, 0, '744', 'Islas Svalbard y Jan Mayen');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (210, 0, '748', 'Swazilandia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (211, 0, '752', 'Suecia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (212, 0, '756', 'Suiza');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (213, 0, '760', 'Siria');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (214, 0, '762', 'Tajikistan');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (215, 0, '764', 'Tailandia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (216, 0, '768', 'Togo');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (217, 0, '772', 'Tokelau');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (218, 0, '776', 'Tonga');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (219, 0, '780', 'Trinidad y Tobago');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (220, 0, '784', 'Emiratos Árabes Unidos');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (221, 0, '788', 'Tunez');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (222, 0, '792', 'Turquia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (223, 0, '795', 'Turkmenistan');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (224, 0, '796', 'Turks y Islas Caicos');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (225, 0, '798', 'Tuvalu');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (226, 0, '800', 'Uganda');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (227, 0, '804', 'Ucrania');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (228, 0, '807', 'Antigua República Yugoslava de Macedonia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (229, 0, '810', 'Antigua URSS 08/12/1991');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (230, 0, '818', 'Egipto');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (231, 0, '826', 'Reino Unido (incluyendo Isla de Man e Islas Channel)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (232, 0, '834', 'Tanzania');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (233, 0, '840', 'Estados Unidos');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (234, 0, '850', 'Islas Vírgenes Estados Unidos');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (235, 0, '854', 'Burkina Faso');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (236, 0, '858', 'Uruguay');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (237, 0, '860', 'Uzbekistan');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (238, 0, '862', 'Venezuela');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (239, 0, '876', 'Wallis y Futuna');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (240, 0, '882', 'Samoa (antes Samoa Oriental)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (241, 0, '887', 'Yemen');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (242, 0, '891', 'Yugoslavia (ahora Serbia y Montenegro) 01/01/1992');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (243, 0, '894', 'Zambia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (244, 0, '997', 'Apátrida Nacionalidad');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (245, 0, '998', 'Nacido en el mar');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (246, 0, '999', 'Desconocido');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (1, 0, '004', 'Afganistán');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (2, 0, '008', 'Albania');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (3, 0, '010', 'Antártida (definido aquí como todo elsur de la latitud 60°S) ');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (4, 0, '012', 'Argelia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (5, 0, '016', 'Samoa Americana ');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (6, 0, '020', 'Andorra');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (7, 0, '024', 'Angola');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (8, 0, '028', 'Antigua y Barbuda');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (9, 0, '031', 'Azerbaiján');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (10, 0, '032', 'Argentina');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (11, 0, '036', 'Australia (incluyendo Ashmore, Islas Cartier y Islas Mar Coral)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (12, 0, '040', 'Austria');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (13, 0, '044', 'Bahamas');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (14, 0, '048', 'Bahrain');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (15, 0, '050', 'Bangladesh');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (16, 0, '051', 'Armenia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (17, 0, '052', 'Barbados');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (18, 0, '056', 'Bélgica');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (19, 0, '060', 'Bermuda');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (20, 0, '064', 'Bhután');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (21, 0, '068', 'Bolivia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (22, 0, '070', 'Bosnia y Herzegovina');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (23, 0, '072', 'Botswana');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (24, 0, '074', 'Isla Bouvet');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (25, 0, '076', 'Brasil');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (26, 0, '084', 'Belice');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (27, 0, '090', 'Islas Salomón');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (28, 0, '092', 'Islas Vírgenes Británicas');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (29, 0, '096', 'Brunei');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (30, 0, '100', 'Bulgaria');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (31, 0, '104', 'Myanmar (Birmania)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (32, 0, '108', 'Burundi');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (33, 0, '112', 'Bielorrusia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (34, 0, '116', 'Camboya');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (35, 0, '120', 'Camerún');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (36, 0, '124', 'Canadá');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (37, 0, '132', 'Cabo Verde');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (38, 0, '136', 'Islas Cayman');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (39, 0, '140', 'República Centro Africana');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (40, 0, '144', 'Sri Lanka');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (41, 0, '148', 'Chad (Tchad)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (42, 0, '152', 'Chile');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (43, 0, '156', 'China (República Popular de China)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (44, 0, '158', 'Taiwan, Provincia de China (República de China)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (45, 0, '162', 'Isla Christmas');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (46, 0, '166', 'Islas Cocos (Keeling)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (47, 0, '170', 'Colombia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (48, 0, '174', 'Comoros');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (49, 0, '175', 'Mayotte');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (50, 0, '178', 'Congo (República del Congo)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (51, 0, '180', 'República Democrática del Congo (antiguamente Zaire)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (52, 0, '184', 'Islas Cook');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (53, 0, '188', 'Costa Rica');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (54, 0, '189', 'Serbia y Montenegro (antesYugoslavia) 01/12/2006');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (55, 0, '191', 'Croacia (Hrvatska)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (56, 0, '192', 'Cuba');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (57, 0, '196', 'Chipre');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (58, 0, '200', 'Antigua Checoslovaquia 01/01/1993');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (59, 0, '203', 'República Checa');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (60, 0, '204', 'Benin');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (61, 0, '208', 'Dinamarca');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (62, 0, '212', 'Dominica');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (63, 0, '214', 'República Dominicana');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (64, 0, '218', 'Ecuador');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (65, 0, '222', 'El Salvador');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (66, 0, '226', 'Guinea Ecuatorial');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (67, 0, '231', 'Etiopia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (68, 0, '232', 'Eritrea');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (69, 0, '233', 'Estonia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (70, 0, '234', 'Islas Feroe');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (71, 0, '238', 'Islas Falkland');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (72, 0, '239', 'Georgia Sur y las Islas Sandwich del Sur');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (73, 0, '242', 'Fiji');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (74, 0, '246', 'Finlandia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (75, 0, '250', 'Francia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (76, 0, '254', 'Guyana Francesa');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (77, 0, '258', 'Polinesia Francesa (incluyendo Isla Clipperton)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (78, 0, '260', 'Territorios Franceses del Sur');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (79, 0, '262', 'Yibuti');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (80, 0, '266', 'Gabón');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (81, 0, '268', 'Georgia (representó previamente las islas de Gilbert y de Ellice)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (82, 0, '270', 'Gambia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (83, 0, '275', 'Territorios Palestinos Ocupados');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (84, 0, '276', 'Alemania');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (85, 0, '288', 'Ghana');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (86, 0, '292', 'Gibraltar');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (87, 0, '296', 'Kiribati');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (88, 0, '300', 'Grecia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (89, 0, '304', 'Groenlandia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (90, 0, '308', 'Granada');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (91, 0, '312', 'Guadalupe');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (92, 0, '316', 'Guam');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (93, 0, '320', 'Guatemala');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (94, 0, '324', 'Guinea');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (95, 0, '328', 'Guyana');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (96, 0, '332', 'Haiti');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (97, 0, '334', 'Isla Head y Islas McDonald');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (98, 0, '336', 'El Vaticano');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (99, 0, '340', 'Honduras');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (100, 0, '344', 'Hong Kong');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (101, 0, '348', 'Hungría');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (102, 0, '352', 'Islandia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (103, 0, '356', 'India');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (104, 0, '360', 'Indonesia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (105, 0, '364', 'Irán');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (106, 0, '368', 'Irak');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (107, 0, '372', 'Irlanda');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (108, 0, '376', 'Israel');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (109, 0, '380', 'Italia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (110, 0, '384', 'Costa de Marfil');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (111, 0, '388', 'Jamaica');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (112, 0, '392', 'Japón');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (113, 0, '398', 'Kazajstán');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (114, 0, '400', 'Jordania');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (115, 0, '404', 'Kenia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (116, 0, '408', 'República Popular Democrática de Corea (Corea del Norte)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (117, 0, '410', 'República de Corea (Corea del Sur)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (118, 0, '414', 'Kuwait');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (119, 0, '417', 'Kirguizstán');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (120, 0, '418', 'República Propular Democrática de Laos');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (121, 0, '422', 'Líbano');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (122, 0, '426', 'Lesotho');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (123, 0, '428', 'Letonia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (124, 0, '430', 'Liberia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (125, 0, '434', 'Libia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (126, 0, '438', 'Liechtenstein');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (127, 0, '440', 'Lituania');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (128, 0, '442', 'Luxemburgo');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (129, 0, '446', 'Macao (Macau)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (130, 0, '450', 'Madagascar');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (131, 0, '454', 'Malawi');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (132, 0, '458', 'Malasia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (133, 0, '462', 'Maldivas');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (134, 0, '466', 'Mali');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (135, 0, '470', 'Malta');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (136, 0, '474', 'Martinica');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (137, 0, '478', 'Mauritania');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (138, 0, '480', 'Mauricio');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (139, 0, '484', 'México');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (140, 0, '492', 'Mónaco');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (141, 0, '496', 'Mongolia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (142, 0, '498', 'Moldavia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (143, 0, '499', 'República de Montenegro');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (144, 0, '500', 'Montserrat');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (145, 0, '504', 'Marruecos');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (146, 0, '508', 'Mozambique');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (147, 0, '512', 'Omán');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (148, 0, '516', 'Namibia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (149, 0, '520', 'Nauru');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (150, 0, '524', 'Nepal');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (151, 0, '528', 'Holanda');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (152, 0, '530', 'Antillas Holandesas');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (153, 0, '533', 'Aruba');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (154, 0, '540', 'Nueva Caledonia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (155, 0, '548', 'Vanuatu');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (156, 0, '554', 'Nueva Zelanda');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (157, 0, '558', 'Nicaragua');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (158, 0, '562', 'Níger');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (159, 0, '566', 'Nigeria');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (160, 0, '570', 'Niue');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (161, 0, '574', 'Isla Norfolk');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (162, 0, '578', 'Noruega');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (163, 0, '580', 'Islas Marianas');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (164, 0, '581', 'Islas Menores y Remotas de Estados Unidos');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (165, 0, '583', 'Estados Federados de Micronesia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (166, 0, '584', 'Islas Marshall');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (167, 0, '585', 'Palau');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (168, 0, '586', 'Pakistán');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (169, 0, '591', 'Panamá');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (170, 0, '598', 'Papua Nueva Guinea');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (171, 0, '600', 'Paraguay');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (172, 0, '604', 'Perú');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (173, 0, '608', 'Filipinas');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (174, 0, '612', 'Islas Pitcairn');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (175, 0, '616', 'Polonia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (176, 0, '620', 'Portugal');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (177, 0, '624', 'Guinea-Bissau');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (178, 0, '626', 'Timor Oriental');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (179, 0, '630', 'Puerto Rico');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (180, 0, '634', 'Qatar');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (181, 0, '638', 'Reunión');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (182, 0, '642', 'Rumania');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (183, 0, '643', 'Rusia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (184, 0, '646', 'Ruanda');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (185, 0, '654', 'Santa Helena (incluyendo Isla Ascensión y otras dependencias)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (186, 0, '659', 'San Kitts y Nevis');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (187, 0, '660', 'Anguilla');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (188, 0, '662', 'Santa Lucia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (189, 0, '666', 'San Pierre y Miquelon');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (190, 0, '670', 'Sant Vincent');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (191, 0, '674', 'San Marino');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (192, 0, '678', 'Santo Tomé y Principe');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (193, 0, '682', 'Arabia Saudí');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (194, 0, '686', 'Senegal');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (195, 0, '688', 'República de Serbia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (196, 0, '690', 'Seychelles');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (197, 0, '694', 'Sierra Leona');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (198, 0, '702', 'Singapur');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (199, 0, '703', 'Eslovaquia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (200, 0, '704', 'Viet Nam (Vietnam)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (201, 0, '705', 'Eslovenia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (202, 0, '706', 'Somalia');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (203, 0, '710', 'Sudáfrica');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (204, 0, '716', 'Zimbabwe');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (205, 0, '724', 'España');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (206, 0, '732', 'Sahara Occidental (antiguamente Sahara Español)');
insert into ADM_PAISES (X_PAIS, L_BAJA, C_PAIS, T_PAIS) values (207, 0, '736', 'Sudan');

commit;