CREATE TABLE PRD_IMPRESOS
(
  X_PRODUCTO        NUMBER(19)                  NOT NULL,
  T_PRODUCTO        VARCHAR2(255 CHAR),
  T_PLANTILLA       VARCHAR2(255 CHAR),
  N_POSICION        NUMBER(19),
  C_TIPOIMPRESION   VARCHAR2(255 CHAR),
  N_TIPOPRODUCTO    NUMBER(10),
  N_TIPOCODBARRAS   NUMBER(10),
  BIB_X_BIBLIOTECA  NUMBER(19)
);

ALTER TABLE PRD_IMPRESOS ADD (
  PRIMARY KEY
 (X_PRODUCTO)
    USING INDEX
    TABLESPACE TS_LIBRAE_DATOS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));

ALTER TABLE PRD_IMPRESOS ADD (
  UNIQUE (T_PRODUCTO)
    USING INDEX
    TABLESPACE TS_LIBRAE_DATOS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE PRD_IMPRESOS ADD (
  CONSTRAINT FK1749A355E19E84CC
 FOREIGN KEY (BIB_X_BIBLIOTECA)
 REFERENCES ADM_BIBLIOTECAS (X_BIBLIOTECA));