UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Infantil'
where X_TIPO_LECTOR=3;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Adulto'
where X_TIPO_LECTOR=2;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Lector institucional'
where X_TIPO_LECTOR=4;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Colectivo'
where X_TIPO_LECTOR=6;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Biblioteca sucursal'
where X_TIPO_LECTOR=5;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Biblioteca intermediaria'
where X_TIPO_LECTOR=7;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Genérico'
where X_TIPO_LECTOR=10;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Temporal'
where X_TIPO_LECTOR=9;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Invalido perdida'
where X_TIPO_LECTOR=11;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Modificar lector'
where X_TIPO_LECTOR=14;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Club de lectura'
where X_TIPO_LECTOR=15;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Invalidao dir. perdida'
where X_TIPO_LECTOR=16;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Personal BIB'
where X_TIPO_LECTOR=47;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Moroso'
where X_TIPO_LECTOR=61;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Investigador'
where X_TIPO_LECTOR=64;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Estudiante universitario'
where X_TIPO_LECTOR=65;

UPDATE LEC_TIPO_LECTORES
SET T_DESCRIPCION_TIPO_LECTOR='Usuario interno'
where X_TIPO_LECTOR=67;
