//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vhudson-jaxb-ri-2.1-520
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2009.12.01 at 12:50:36 PM CET
//

package org.librae.adminconfig.webapp.ws.dto;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for Horario complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name=&quot;Horario&quot;&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;fechaActualizacion&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}dateTime&quot;/&gt;
 *         &lt;element name=&quot;horariosInt&quot; type=&quot;{http://horario.ws.librae.org/}HorarioInt&quot; maxOccurs=&quot;unbounded&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Horario", propOrder = { "fechaActualizacion", "horariosInt" })
@XmlRootElement
public class Horario {

    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaActualizacion;
    @XmlElement(required = true)
    protected List<HorarioInt>     horariosInt;

    /**
     * Gets the value of the fechaActualizacion property.
     * 
     * @return possible object is {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getFechaActualizacion() {
        return fechaActualizacion;
    }

    /**
     * Sets the value of the fechaActualizacion property.
     * 
     * @param value
     *            allowed object is {@link XMLGregorianCalendar }
     */
    public void setFechaActualizacion(XMLGregorianCalendar value) {
        fechaActualizacion = value;
    }

    /**
     * Gets the value of the horariosInt property.
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the horariosInt property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getHorariosInt().add(newItem);
     * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HorarioInt }
     */
    public List<HorarioInt> getHorariosInt() {
        if (horariosInt == null) {
            horariosInt = new ArrayList<HorarioInt>();
        }
        return horariosInt;
    }

    /**
     * @param horariosInt
     *            the horariosInt to set
     */
    public void setHorariosInt(List<HorarioInt> horariosInt) {
        this.horariosInt = horariosInt;
    }

}
