//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.01 at 12:50:36 PM CET 
//


package org.librae.adminconfig.webapp.ws.dto;

import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;

public class RespuestaElement
    extends JAXBElement<Respuesta>
{

    protected final static QName NAME = new QName("http://horario.ws.librae.org/", "Respuesta");

    public RespuestaElement(Respuesta value) {
        super(NAME, ((Class) Respuesta.class), null, value);
    }

}
