CREATE TABLESPACE "TS_TABLAS_LIBRAE_APP"
LOGGING DATAFILE 'd:\oracle\oradata\oracle2\TS_TABLAS_LIBREA_APP.dbf'
SIZE 20M;

CREATE TABLESPACE "TS_INDICES_LIBRAE_APP"
LOGGING DATAFILE 'D:\ORACLE\ORADATA\ORACLE\TS_INDICES_LIBREA_APP.DBF'
SIZE 20M;

---- CREACI?N DE USUARIO ----

CREATE USER librae_user IDENTIFIED BY librae_pwd
DEFAULT TABLESPACE TS_TABLAS_LIBRAE_APP
TEMPORARY TABLESPACE TEMP;


---- ROLES ----

GRANT CONNECT,
      RESOURCE,
      UNLIMITED TABLESPACE
TO librae_user; 