DROP TABLE CIR_VIEW_PRESTAMOS_DIA;
CREATE VIEW CIR_VIEW_PRESTAMOS_DIA AS
select concat(p.X_PRESTAMO, 'N') as X_CIR_VIEW_PRESTAMOS_DIA, e.X_EJEMPLAR as EJEMPLAR_X_EJEMPLAR, tp.X_TIPO_PRESTAMO AS TIPO_PRESTAMO_X_TIPO_PRESTAMO, 'N' as L_DEVUELTO
from CIR_PRESTAMOS p, CIR_TIPO_PRESTAMO tp, CAT_EJEMPLARES e
where tp.X_TIPO_PRESTAMO = p.T_PRESTAMO_X_T_PRESTAMO
and p.EJEMPLAR = e.X_EJEMPLAR
and tp.C_TIPO_PRESTAMO = 'SA'
UNION
select concat(ph.X_PRESTAMO_HIST, 'S') as X_CIR_VIEW_PRESTAMOS_DIA, e.X_EJEMPLAR as EJEMPLAR_X_EJEMPLAR, tp.X_TIPO_PRESTAMO AS TIPO_PRESTAMO_X_TIPO_PRESTAMO, 'S' as L_DEVUELTO
from CIR_PRESTAMOS_HIST ph, CIR_TIPO_PRESTAMO tp, CAT_EJEMPLARES e
where tp.X_TIPO_PRESTAMO = ph.T_PRESTAMO_X_T_PRESTAMO
and ph.EJE_X_EJEMPAR = e.X_EJEMPLAR
and tp.C_TIPO_PRESTAMO = 'SA'
and to_char(ph.F_DEVOLUCION,'DD/MM/YYYY') = to_char(CURRENT_DATE,'DD/MM/YYYY');
commit;

